const SAMPLE_LESSONS = [
  {
    id: "1",
    title: "Coding the Constellations",
    summary: "Learn sequencing by plotting constellations with grid coordinates.",
    tags: ["Computer Science", "Unplugged", "Mapping"],
    gradeBands: ["K-2", "3-5"],
    duration: "30–45 min",
    format: "Unplugged",
  },
  {
    id: "2",
    title: "Solar Storm Data Dive",
    summary: "Analyze solar flare data and chart patterns over time.",
    tags: ["Data Science", "Space", "Hybrid"],
    gradeBands: ["6-8", "9-12"],
    duration: "45–60 min",
    format: "Hybrid",
  },
  {
    id: "3",
    title: "Magnetosphere Maze",
    summary: "Use algorithms to navigate a particle through a magnetic field.",
    tags: ["Computer Science", "Physics", "Unplugged"],
    gradeBands: ["3-5", "6-8"],
    duration: "30–45 min",
    format: "Unplugged",
  },
  {
    id: "4",
    title: "Planetary Patterns with Python",
    summary: "Intro to loops by modeling orbit patterns.",
    tags: ["Computer Science", "Programming", "Hybrid"],
    gradeBands: ["6-8", "9-12"],
    duration: "60–90 min",
    format: "Hybrid",
  },
  {
    id: "5",
    title: "Ecosystems Data Collection",
    summary: "Collect simple field data and visualize species counts.",
    tags: ["Data Science", "Biology", "Field"],
    gradeBands: ["3-5", "6-8"],
    duration: "45–60 min",
    format: "Hybrid",
  },
  {
    id: "6",
    title: "Bridge Building Challenge",
    summary: "Engineering activity to explore forces and structures.",
    tags: ["Engineering", "STEM", "Hands-on"],
    gradeBands: ["6-8", "9-12"],
    duration: "60–90 min",
    format: "Unplugged",
  },
  {
    id: "7",
    title: "Simple Circuits",
    summary: "Build basic circuits to learn about electricity and safety.",
    tags: ["Physics", "Engineering", "Hands-on"],
    gradeBands: ["3-5", "6-8"],
    duration: "30–45 min",
    format: "Hybrid",
  },
  {
    id: "8",
    title: "Binary Stars & Binary Numbers",
    summary: "Decode messages using binary inspired by star systems.",
    tags: ["Computer Science", "Math", "Unplugged"],
    gradeBands: ["3-5", "6-8"],
    duration: "30–45 min",
    format: "Unplugged",
  },
];

export default SAMPLE_LESSONS;
